package ggv.ayush.bcatrack

//list of students with  name and rollNo

val BcaStudents = listOf(
    Student("ABHISHEK PAUL", 1),
    Student("ADITYA KUMAR SINGH", 2),
    Student("AKASH SHARMA", 3),
    Student("ANJALI", 4),
    Student("ANSH TRIPATHI", 5),
    Student("ARNOLD MINJ", 6),
    Student("ARVIND SONI", 7),
    Student("AYUSH RAI", 8),
    Student("B. VAMSI", 9),
    Student("BIPASHA MALLICK", 10),
    Student("CHITESH KUMAR SAHU", 11),
    Student("HARSHVARDHAN KUMAR", 12),
    Student("HEENA KUMARI SAHU", 13),
    Student("HITESH KHUNTE", 14),
    Student("HRISHABH YADAV", 15),
    Student("KRISHNA PANDEY", 16),
    Student("KUMAR SHUBHRANSHU", 17),
    Student("KUMARI AASHI", 18),
    Student("KUNAL PRASAD", 19),
    Student("LOKESH KUMAR GHRITLAHARE", 20),
    Student("MADHU DUBEY", 21),
    Student("MAHIMA NETAM", 22),
    Student("MAYANK SAIYAM", 23),
    Student("MUSKAN GUPTA", 24),
    Student("OMKAR NAYAK", 25),
    Student("OMKAR PRASAD DHRUW", 26),
    Student("PARASMANI KHUNTE", 27),
    Student("PRABHANSHU KERKETTA", 28),
    Student("PRATIK MUKHERJEE", 29),
    Student("RAHUL NISHAD", 30),
    Student("RAJA YADAV", 31),
    Student("RISHABH JOGI", 32),
    Student("RISHABH VAISHNAV", 33),
    Student("RIYA SINGH", 34),
    Student("SAGAR SINGH", 35),
    Student("SAKSHAM SHRIVASTAVA", 36),
    Student("SARTHAK BHAGAT", 37),
    Student("SATYANSH KAHARA", 38),
    Student("SAURABH KUMAR YADAV", 39),
    Student("SAURABH MAURYA", 40),
    Student("SHREYA SINGH", 41),
    Student("SHUBHAM CHANDRAKAR A", 42),
    Student("SHUBHAM SINGH", 43),
    Student("SONAL DHRUW", 44),
    Student("SRISHTY JHA", 45),
    Student("SUJAL ADITYA MINJ", 46),
    Student("SUSHIL PATEL", 47),
    Student("TEJ PRATAP SHARMA", 48),
    Student("TRIPURARI NATH", 49),
    Student("VAIBHAV KHARE", 50),
    Student("VARUN KAIWART", 51)
)

val BscStudents = List(75) { index ->
    Student("Student ${index + 1}", index + 1)
}